#INIT CATCCS CTASC
#ROUTE TKK_MEGURO

[Easy]
revcenter = 1

[Define]
lamp = 1
system = 6
door = 1

[Ato]
fmdoor = 1

[Tasc]
decel = 3.5
range = 0.45

adjust = 0.8
; 地上子位置補正の設定
; 過走するの場合は0.5～0.7程度
; 手前位置の場合は0.9～1.0程度

[TascPattern]
p1pre = 11
p2pre = 12
p3pre = 13
; パターンプリセットの設定
; 11=MEGURO_P1, 12=MEGURO_P2, 13=MEGURO_P3(default)
; 16=MEGURO_OP_P2(openBVE用 P2係数プリセット)
; openBVEでは p2pre を 16 にする(暫定)

p3fix = 1

[Extra]
notchlag = 200
; ノッチ表示灯タイムラグの設定
; 100～200[ms]が適当な値、0でリアルタイムになる
; 5080系では、左側のB灯がこれに対応

[Atcsw]
type = 10
; ATC切替SW仕様の設定
; 10=非設 － ATC － ATO/TASC － 構内

[Key]
type = 10
; マスコンキー仕様の設定
; 10=東急 ← 切
; 11=東急 ← 切 → 営団

[Brake]
kaisei = 1
; 回生失効の設定(未対応)
; 0=回生失効しない
; 1～3=回生失効レベル

[Limit]
speed = 110
